host:
  port: 8080

mysql:
  user: root
  password: 1234
  host: 127.0.0.1
  port: 3306
  database: test
  maxIdleConn: 10
  maxOpenConn: 100

redis:
  host: 127.0.0.1
  port: 6379
  password: 1234
  db: 0